name: upload and download
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  create:
    runs-on: ubuntu-latest
    steps:
      - name: make
        run: |
          pwd
          echo " make 2 test.txt"
          touch test.txt
          echo "aa" > test.txt
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: txt-files
          path: ./
  download:
    needs: create
    runs-on: ubuntu-latest
    steps:
      - name: download
        uses: actions/download-artifact@v3
        with:
          name: txt-files
      - name: output txt-files
        run: |
          pwd
          ls
          cat test.txt