name: deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: make
        run: |
          pwd
          echo " make test.txt"
          touch test.txt
          echo "aa" > test.txt
      - name: upload
        uses: actions/upload-artifact@v3
        with:
          name: txt-files
          path: ./